// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzowinqgpaiydgwbksku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6b3dpbnFncGFpeWRnd2Jrc2t1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNTI1NzQsImV4cCI6MjA1ODYyODU3NH0.S1Fnc5SGPO7hjIi3vRd5IuogRLW0SXy0nmwC2pdSyVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);